from app.schemas import ResearchRun


AI_CAPEX_SEMIS_RESEARCH_RUN = ResearchRun.model_validate(
    {
        "question": "Is AI capex becoming a risk for semiconductors and hyperscalers?",
        "classification": "industry_cycle_narrative",
        "timestamp": "Prototype run | hardcoded backend data",
        "scenario": "AI infrastructure capex ROI debate",
        "headline": "AI capex remains a semiconductor tailwind, but hyperscaler ROI proof is becoming the gating risk for the whole chain.",
        "thesis": "The AI capex setup is not simply bullish or bearish. Accelerator, networking, and memory demand can keep supporting semiconductor fundamentals, while hyperscalers face rising depreciation, power constraints, and free-cash-flow pressure. The critical question is whether AI revenue and productivity gains arrive fast enough to justify the next leg of infrastructure spending.",
        "judgment": {
            "title": "Research judgment",
            "stance": "Constructive for suppliers, increasingly ROI-sensitive for buyers",
            "summary": "Treat AI capex as an industry-cycle and narrative-risk problem. Semiconductors benefit while order visibility, utilization, and pricing remain strong. Hyperscalers carry the burden of proving returns through cloud growth, AI product monetization, and margin durability. The adverse branch is a capex digestion cycle if depreciation and power needs outpace visible revenue.",
            "watchItems": [
                "Hyperscaler capex growth versus AI revenue disclosure",
                "GPU, networking, and memory order durability",
                "Depreciation and free-cash-flow pressure",
                "Power, data-center, and supply-chain bottlenecks",
            ],
        },
        "keyDrivers": [
            "AI capex intensity",
            "Accelerator demand",
            "Networking and memory",
            "Hyperscaler free cash flow",
            "Depreciation burden",
            "Utilization / ROI",
            "Supply constraints",
            "Multiple expectations",
        ],
        "metrics": [
            {
                "label": "Capex impulse",
                "value": "Elevated",
                "detail": "Illustrative AI infrastructure spending cycle",
                "tone": "cyan",
            },
            {
                "label": "Supplier tailwind",
                "value": "Strong",
                "detail": "Accelerators, networking, and memory remain advantaged",
                "tone": "emerald",
            },
            {
                "label": "Buyer burden",
                "value": "Rising",
                "detail": "Depreciation and power costs pressure hyperscaler FCF",
                "tone": "amber",
            },
            {
                "label": "Skeptic flag",
                "value": "ROI proof",
                "detail": "Capex digestion risk rises if monetization lags",
                "tone": "rose",
            },
        ],
        "agents": [
            {
                "name": "Planner Agent",
                "role": "Classifies the question and extracts the sector driver map.",
                "status": "complete",
                "duration": "00:06",
                "output": [
                    "Research type: industry_cycle_narrative",
                    "Shock: AI capex intensity and ROI scrutiny",
                    "Affected sectors: semiconductors and hyperscalers",
                    "Drivers: accelerators, networking, FCF, depreciation, ROI, multiples",
                ],
            },
            {
                "name": "Data Agent",
                "role": "Stages infrastructure-cycle indicators for the demo run.",
                "status": "complete",
                "duration": "00:09",
                "output": [
                    "Capex-intensity, supplier-demand, and depreciation placeholders attached",
                    "Power and data-center constraint flags staged",
                    "No live filings, SEC, market-data, or model calls in this demo",
                ],
            },
            {
                "name": "Framework Agent",
                "role": "Selects the analytical lens for the transmission chain.",
                "status": "complete",
                "duration": "00:07",
                "output": [
                    "Framework: industry-cycle analysis + narrative-risk test",
                    "Primary tension: semiconductor revenue tailwind versus hyperscaler ROI burden",
                ],
            },
            {
                "name": "Skeptic Agent",
                "role": "Challenges the assumption that AI capex can compound indefinitely.",
                "status": "complete",
                "duration": "00:05",
                "output": [
                    "Capex can pull forward demand and create digestion risk",
                    "Hyperscalers must show monetization before depreciation pressure builds",
                    "Supplier multiples are vulnerable if order growth merely normalizes",
                ],
            },
            {
                "name": "Synthesis Agent",
                "role": "Produces the map, evidence board, bull/bear view, and memo.",
                "status": "complete",
                "duration": "00:08",
                "output": [
                    "Transmission map assembled",
                    "Claims labeled by evidence type",
                    "Memo avoids recommendations and price targets",
                ],
            },
        ],
        "transmissionNodes": [
            {
                "id": "ai-capex-boom",
                "label": "AI capex boom",
                "subtitle": "Infrastructure budgets stay elevated",
                "driver": "AI capex intensity",
                "evidenceType": "Narrative signal",
                "confidence": "Medium/High",
                "researchImplication": "Start by separating supplier revenue upside from buyer return burden.",
                "whyItMatters": "The same spending cycle can be bullish for semis and riskier for hyperscaler cash flows.",
                "polarity": "neutral",
                "x": 0,
                "y": 250,
            },
            {
                "id": "accelerator-demand",
                "label": "Accelerator demand",
                "subtitle": "GPU and custom silicon orders",
                "driver": "Accelerator demand",
                "evidenceType": "Framework inference",
                "confidence": "Medium/High",
                "researchImplication": "Supplier fundamentals remain supported while order duration and utilization stay visible.",
                "whyItMatters": "Accelerators are the most direct revenue channel from AI capex into semiconductor earnings.",
                "polarity": "positive",
                "x": 340,
                "y": 50,
            },
            {
                "id": "semi-revenue",
                "label": "Semiconductor revenue",
                "subtitle": "Content growth and pricing power",
                "driver": "Semiconductor fundamentals",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "Focus on backlog quality and breadth beyond the leading accelerator supplier.",
                "whyItMatters": "Revenue durability determines whether the AI cycle is broadening or concentrated.",
                "polarity": "positive",
                "x": 710,
                "y": 50,
            },
            {
                "id": "networking-memory",
                "label": "Networking and memory",
                "subtitle": "AI clusters need adjacent content",
                "driver": "Networking and memory",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "Track whether AI demand spreads to networking, HBM, storage, and power components.",
                "whyItMatters": "Broader content growth makes the supplier tailwind more durable and less single-product dependent.",
                "polarity": "positive",
                "x": 340,
                "y": 190,
            },
            {
                "id": "supply-bottlenecks",
                "label": "Supply bottlenecks",
                "subtitle": "Capacity, packaging, and power",
                "driver": "Supply constraints",
                "evidenceType": "Open question",
                "confidence": "Medium",
                "researchImplication": "Constraints can support pricing but also limit deployment and revenue recognition.",
                "whyItMatters": "Bottlenecks influence both supplier margins and hyperscaler deployment timelines.",
                "polarity": "mixed",
                "x": 710,
                "y": 190,
            },
            {
                "id": "hyperscaler-budgets",
                "label": "Hyperscaler budgets",
                "subtitle": "Cloud platforms fund the buildout",
                "driver": "Hyperscaler capex",
                "evidenceType": "Narrative signal",
                "confidence": "Medium",
                "researchImplication": "Assess whether capex growth is still discretionary or becoming table stakes.",
                "whyItMatters": "Hyperscalers are the buyer side of the cycle and carry the capital-allocation scrutiny.",
                "polarity": "mixed",
                "x": 340,
                "y": 330,
            },
            {
                "id": "depreciation-fcf",
                "label": "Depreciation / FCF",
                "subtitle": "Spending turns into expense burden",
                "driver": "Hyperscaler free cash flow",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "Model capex as a future depreciation and free-cash-flow test, not only growth investment.",
                "whyItMatters": "Depreciation can pressure reported margins even when demand remains strategically important.",
                "polarity": "risk",
                "x": 710,
                "y": 330,
            },
            {
                "id": "power-data-centers",
                "label": "Power and data centers",
                "subtitle": "Physical deployment constraints",
                "driver": "Infrastructure capacity",
                "evidenceType": "Open question",
                "confidence": "Medium",
                "researchImplication": "Power availability can become a capex bottleneck or a cost escalator.",
                "whyItMatters": "AI infrastructure is constrained by physical buildout, not just chip supply.",
                "polarity": "risk",
                "x": 0,
                "y": 520,
            },
            {
                "id": "roi-proof",
                "label": "ROI proof",
                "subtitle": "Revenue and productivity must show up",
                "driver": "Utilization / ROI",
                "evidenceType": "Open question",
                "confidence": "Medium",
                "researchImplication": "The next phase needs evidence that AI products and cloud usage earn the spend.",
                "whyItMatters": "ROI proof is the bridge between high capex and investor tolerance for lower near-term FCF.",
                "polarity": "risk",
                "x": 340,
                "y": 500,
            },
            {
                "id": "capex-pause-risk",
                "label": "Capex pause risk",
                "subtitle": "Digestion cycle if returns lag",
                "driver": "Order durability",
                "evidenceType": "Framework inference",
                "confidence": "Low/Medium",
                "researchImplication": "Supplier estimates are most vulnerable if buyers slow the rate of new orders.",
                "whyItMatters": "Even a pause after rapid growth can reset narrative expectations and multiples.",
                "polarity": "risk",
                "x": 710,
                "y": 500,
            },
            {
                "id": "multiple-expectations",
                "label": "Multiple expectations",
                "subtitle": "Narrative premium meets proof burden",
                "driver": "Multiple expectations",
                "evidenceType": "Narrative signal",
                "confidence": "Low/Medium",
                "researchImplication": "Valuation sensitivity rises when the debate shifts from scarcity to return on capital.",
                "whyItMatters": "High expectations can create downside even when fundamentals remain strong but decelerate.",
                "polarity": "mixed",
                "x": 340,
                "y": 650,
            },
            {
                "id": "terminal-judgment",
                "label": "Semis and cloud judgment",
                "subtitle": "Supplier tailwind versus buyer burden",
                "driver": "Cycle judgment",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "The conclusion is conditional: supplier upside persists if hyperscaler ROI proof keeps funding intact.",
                "whyItMatters": "The chain breaks if buyers slow spending before suppliers diversify demand and margins.",
                "polarity": "mixed",
                "x": 710,
                "y": 650,
            },
        ],
        "transmissionEdges": [
            {
                "id": "e1",
                "source": "ai-capex-boom",
                "target": "accelerator-demand",
                "label": "funds orders",
                "polarity": "positive",
            },
            {
                "id": "e2",
                "source": "accelerator-demand",
                "target": "semi-revenue",
                "label": "drives content growth",
                "polarity": "positive",
            },
            {
                "id": "e3",
                "source": "ai-capex-boom",
                "target": "networking-memory",
                "label": "broadens spend",
                "polarity": "positive",
            },
            {
                "id": "e4",
                "source": "networking-memory",
                "target": "supply-bottlenecks",
                "label": "tests capacity",
                "polarity": "mixed",
            },
            {
                "id": "e5",
                "source": "ai-capex-boom",
                "target": "hyperscaler-budgets",
                "label": "raises spend",
                "polarity": "mixed",
            },
            {
                "id": "e6",
                "source": "hyperscaler-budgets",
                "target": "depreciation-fcf",
                "label": "creates burden",
                "polarity": "risk",
            },
            {
                "id": "e7",
                "source": "power-data-centers",
                "target": "depreciation-fcf",
                "label": "adds cost",
                "polarity": "risk",
            },
            {
                "id": "e8",
                "source": "hyperscaler-budgets",
                "target": "roi-proof",
                "label": "requires proof",
                "polarity": "risk",
            },
            {
                "id": "e9",
                "source": "roi-proof",
                "target": "capex-pause-risk",
                "label": "if returns lag",
                "polarity": "risk",
            },
            {
                "id": "e10",
                "source": "capex-pause-risk",
                "target": "semi-revenue",
                "label": "can slow orders",
                "polarity": "risk",
            },
            {
                "id": "e11",
                "source": "supply-bottlenecks",
                "target": "terminal-judgment",
                "label": "changes deployment pace",
                "polarity": "mixed",
            },
            {
                "id": "e12",
                "source": "depreciation-fcf",
                "target": "terminal-judgment",
                "label": "pressures buyers",
                "polarity": "risk",
            },
            {
                "id": "e13",
                "source": "multiple-expectations",
                "target": "terminal-judgment",
                "label": "raises proof burden",
                "polarity": "mixed",
            },
            {
                "id": "e14",
                "source": "semi-revenue",
                "target": "terminal-judgment",
                "label": "supports suppliers",
                "polarity": "positive",
            },
        ],
        "charts": [
            {
                "title": "AI capex intensity",
                "subtitle": "Illustrative infrastructure spend path",
                "unit": "idx",
                "tone": "cyan",
                "data": [
                    {"period": "Q1", "value": 100},
                    {"period": "Q2", "value": 118},
                    {"period": "Q3", "value": 136},
                    {"period": "Q4", "value": 150},
                    {"period": "Q5", "value": 158},
                ],
            },
            {
                "title": "Supplier demand",
                "subtitle": "Accelerators versus adjacent content",
                "unit": "idx",
                "tone": "emerald",
                "data": [
                    {"period": "Q1", "value": 100, "comparison": 100},
                    {"period": "Q2", "value": 126, "comparison": 112},
                    {"period": "Q3", "value": 148, "comparison": 124},
                    {"period": "Q4", "value": 162, "comparison": 137},
                    {"period": "Q5", "value": 168, "comparison": 145},
                ],
            },
            {
                "title": "Depreciation burden",
                "subtitle": "Capex converts into future expense",
                "unit": "idx",
                "tone": "amber",
                "data": [
                    {"period": "Q1", "value": 100},
                    {"period": "Q2", "value": 109},
                    {"period": "Q3", "value": 121},
                    {"period": "Q4", "value": 135},
                    {"period": "Q5", "value": 149},
                ],
            },
            {
                "title": "ROI proof gap",
                "subtitle": "Spend growth versus visible monetization",
                "unit": "idx",
                "tone": "rose",
                "data": [
                    {"period": "Q1", "value": 8, "comparison": 12},
                    {"period": "Q2", "value": 14, "comparison": 22},
                    {"period": "Q3", "value": 21, "comparison": 34},
                    {"period": "Q4", "value": 28, "comparison": 45},
                    {"period": "Q5", "value": 35, "comparison": 52},
                ],
            },
        ],
        "evidence": [
            {
                "claim": "AI infrastructure capex is a direct demand channel for accelerators, networking, memory, and related semiconductor content.",
                "type": "Framework inference",
                "confidence": "Medium/High",
                "importance": "High",
                "driver": "Accelerator demand",
                "sourceLabel": "AI infrastructure driver map",
                "sourceType": "Internal framework",
                "sourceQuality": "Medium",
            },
            {
                "claim": "Hyperscaler capex creates future depreciation and free-cash-flow scrutiny even when the strategic rationale is strong.",
                "type": "Framework inference",
                "confidence": "Medium",
                "importance": "High",
                "driver": "Hyperscaler free cash flow",
                "sourceLabel": "Capital intensity framework",
                "sourceType": "Framework",
                "sourceQuality": "Medium",
            },
            {
                "claim": "The investor debate can shift from scarcity and growth to utilization, monetization, and return on invested capital.",
                "type": "Narrative signal",
                "confidence": "Medium",
                "importance": "High",
                "driver": "Utilization / ROI",
                "sourceLabel": "Market narrative placeholder",
                "sourceType": "Narrative signal",
                "sourceQuality": "Low",
            },
            {
                "claim": "Power, data-center, advanced packaging, and supply-chain constraints can shape deployment timing.",
                "type": "Open question",
                "confidence": "Medium",
                "importance": "Medium",
                "driver": "Supply constraints",
                "sourceLabel": "Infrastructure diligence list",
                "sourceType": "Open research item",
                "sourceQuality": "Medium",
            },
            {
                "claim": "A capex digestion cycle would most directly pressure semiconductor order growth and valuation expectations.",
                "type": "Framework inference",
                "confidence": "Low/Medium",
                "importance": "High",
                "driver": "Order durability",
                "sourceLabel": "Semiconductor cycle framework",
                "sourceType": "Internal framework",
                "sourceQuality": "Medium",
            },
            {
                "claim": "The central unresolved issue is whether AI products create enough revenue and productivity benefit to sustain spending growth.",
                "type": "Open question",
                "confidence": "Medium",
                "importance": "High",
                "driver": "Utilization / ROI",
                "sourceLabel": "Skeptic agent issue list",
                "sourceType": "Open research item",
                "sourceQuality": "Medium",
            },
        ],
        "bullCase": {
            "title": "Constructive transmission",
            "points": [
                "Hyperscalers keep spending because AI demand improves cloud growth and product monetization.",
                "Accelerator demand broadens into networking, memory, storage, and power components.",
                "Supply constraints support pricing without blocking deployment enough to slow revenue recognition.",
                "High utilization and visible AI revenue keep investors tolerant of elevated capex.",
            ],
        },
        "bearCase": {
            "title": "Adverse transmission",
            "points": [
                "Capex growth runs ahead of visible AI revenue, raising free-cash-flow and depreciation concerns.",
                "Power and data-center constraints make deployments slower and more expensive than expected.",
                "Hyperscalers pause or smooth orders, creating a semiconductor digestion cycle.",
                "Valuation multiples reset if the narrative shifts from scarcity to ROI uncertainty.",
            ],
        },
        "memo": [
            {
                "title": "Bottom line",
                "body": "AI capex is still a powerful semiconductor demand tailwind, but it is becoming a sharper risk question for hyperscalers. The demo view is conditional: spending can remain constructive if utilization and monetization evidence improves before depreciation and free-cash-flow pressure dominate the debate.",
            },
            {
                "title": "Most important driver",
                "body": "The decisive branch is ROI proof. If AI products, cloud usage, and productivity gains become visible, buyers can justify elevated capex and suppliers keep strong order visibility. If proof lags, hyperscalers may slow the next spending wave and semiconductor estimates become more vulnerable.",
            },
            {
                "title": "Evidence standard",
                "body": "This prototype labels claims as framework inference, narrative signal, or open question. It does not use live filings, company guidance, market prices, recommendations, or price targets.",
            },
        ],
        "openQuestions": [
            {
                "question": "Are hyperscalers disclosing enough AI revenue, utilization, or productivity evidence to justify the capex step-up?",
                "whyItMatters": "ROI proof determines whether investors keep funding the buyer-side burden.",
                "owner": "Hyperscaler model follow-up",
            },
            {
                "question": "Is semiconductor demand broadening beyond accelerators into networking, memory, and power components?",
                "whyItMatters": "Breadth makes the supplier cycle more durable and less dependent on one product category.",
                "owner": "Semiconductor diligence",
            },
            {
                "question": "Do power, data-center, or packaging constraints slow deployment enough to change the capex cadence?",
                "whyItMatters": "Physical constraints can turn strong demand into delayed revenue or higher costs.",
                "owner": "Infrastructure follow-up",
            },
        ],
    }
)

__all__ = ["AI_CAPEX_SEMIS_RESEARCH_RUN"]
