from app.schemas import ResearchRun


OIL_AIRLINES_RESEARCH_RUN = ResearchRun.model_validate(
    {
        "question": "What happens to airlines if oil prices rise while consumer demand weakens?",
        "classification": "macro_to_sector_shock",
        "timestamp": "Prototype run | hardcoded backend data",
        "scenario": "Oil shock plus weaker travel demand",
        "headline": "Airlines face margin compression when fuel inflation arrives at the same time as softer discretionary travel demand.",
        "thesis": "The oil-and-airlines setup is a two-sided shock. Higher crude prices push jet-fuel costs higher, while weakening consumer demand limits fare increases and raises load-factor risk. The sector outcome depends on hedging coverage, capacity discipline, balance-sheet flexibility, and whether corporate or premium demand can offset weaker leisure volumes.",
        "judgment": {
            "title": "Research judgment",
            "stance": "Margin-negative unless pricing power and capacity discipline hold",
            "summary": "Treat the scenario as a cost shock colliding with demand elasticity. Airlines can absorb some fuel inflation when demand is strong and fares can reprice, but the adverse branch appears when consumers trade down, load factors soften, and fixed costs amplify small revenue misses into large margin pressure.",
            "watchItems": [
                "Jet-fuel pass-through into fares",
                "Load-factor and booking-curve deterioration",
                "Capacity cuts versus market-share defense",
                "Hedge coverage, liquidity, and leverage",
            ],
        },
        "keyDrivers": [
            "Jet fuel cost",
            "Fare elasticity",
            "Load factors",
            "Capacity discipline",
            "Operating leverage",
            "Hedging coverage",
            "Consumer demand",
            "Margin / free cash flow",
        ],
        "metrics": [
            {
                "label": "Input shock",
                "value": "+25%",
                "detail": "Illustrative crude and jet-fuel cost pressure",
                "tone": "amber",
            },
            {
                "label": "Demand shock",
                "value": "Weakening",
                "detail": "Leisure demand and price tolerance fade",
                "tone": "rose",
            },
            {
                "label": "Pass-through",
                "value": "Limited",
                "detail": "Fares cannot fully offset fuel if consumers pull back",
                "tone": "cyan",
            },
            {
                "label": "Skeptic flag",
                "value": "Load factors",
                "detail": "Small volume misses can hit margins through fixed costs",
                "tone": "emerald",
            },
        ],
        "agents": [
            {
                "name": "Planner Agent",
                "role": "Classifies the question and extracts the sector driver map.",
                "status": "complete",
                "duration": "00:05",
                "output": [
                    "Research type: macro_to_sector_shock",
                    "Shock: oil price rise plus weaker consumer demand",
                    "Affected sector: airlines",
                    "Drivers: jet fuel, fares, load factors, capacity, operating leverage",
                ],
            },
            {
                "name": "Data Agent",
                "role": "Stages airline operating indicators for the demo run.",
                "status": "complete",
                "duration": "00:08",
                "output": [
                    "Fuel-cost and demand-sensitivity placeholders attached",
                    "Load-factor, fare-yield, and hedge-coverage series staged",
                    "No live commodity, TSA, or airline data calls in this demo",
                ],
            },
            {
                "name": "Framework Agent",
                "role": "Selects the analytical lens for the transmission chain.",
                "status": "complete",
                "duration": "00:07",
                "output": [
                    "Framework: input-cost shock + consumer demand shock",
                    "Primary tension: fuel pass-through versus fare elasticity and utilization",
                ],
            },
            {
                "name": "Skeptic Agent",
                "role": "Challenges the assumption that airlines can simply raise fares.",
                "status": "complete",
                "duration": "00:05",
                "output": [
                    "Weak demand can block fuel pass-through",
                    "Capacity cuts may protect margins but reduce revenue growth",
                    "Hedge benefits can be temporary and uneven across carriers",
                ],
            },
            {
                "name": "Synthesis Agent",
                "role": "Produces the map, evidence board, bull/bear view, and memo.",
                "status": "complete",
                "duration": "00:08",
                "output": [
                    "Transmission map assembled",
                    "Claims labeled by evidence type",
                    "Memo avoids recommendations and price targets",
                ],
            },
        ],
        "transmissionNodes": [
            {
                "id": "oil-price-shock",
                "label": "Oil price shock",
                "subtitle": "Crude and jet-fuel benchmarks rise",
                "driver": "Input cost",
                "evidenceType": "Framework inference",
                "confidence": "High",
                "researchImplication": "Start with the cost line before assuming demand or fare recovery can absorb it.",
                "whyItMatters": "Fuel is one of the largest variable costs for airlines and can move faster than ticket pricing.",
                "polarity": "neutral",
                "x": 0,
                "y": 230,
            },
            {
                "id": "jet-fuel-cost",
                "label": "Jet-fuel cost inflation",
                "subtitle": "CASM-ex fuel offset disappears",
                "driver": "Jet fuel cost",
                "evidenceType": "Data",
                "confidence": "Medium/High",
                "researchImplication": "Model fuel expense as the first-order earnings drag in the scenario.",
                "whyItMatters": "Higher fuel prices directly pressure unit costs and near-term margin estimates.",
                "polarity": "negative",
                "x": 340,
                "y": 50,
            },
            {
                "id": "unit-cost-pressure",
                "label": "Unit-cost pressure",
                "subtitle": "Cost per available seat mile rises",
                "driver": "Operating cost",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "Watch whether non-fuel productivity can offset the fuel shock.",
                "whyItMatters": "Unit-cost inflation compresses margins unless fares, mix, or utilization improve.",
                "polarity": "negative",
                "x": 710,
                "y": 50,
            },
            {
                "id": "weak-demand",
                "label": "Weaker consumer demand",
                "subtitle": "Leisure budgets and confidence fade",
                "driver": "Consumer demand",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "Separate premium and corporate demand from price-sensitive leisure demand.",
                "whyItMatters": "A demand slowdown limits how much cost inflation can be passed through to travelers.",
                "polarity": "risk",
                "x": 0,
                "y": 470,
            },
            {
                "id": "fare-elasticity",
                "label": "Fare elasticity",
                "subtitle": "Price increases face resistance",
                "driver": "Fare elasticity",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "Stress-test fare-yield assumptions under weaker booking curves.",
                "whyItMatters": "Pricing power is the key buffer between fuel inflation and margin compression.",
                "polarity": "risk",
                "x": 340,
                "y": 190,
            },
            {
                "id": "yield-pressure",
                "label": "Yield pressure",
                "subtitle": "Fares cannot fully reprice",
                "driver": "Revenue yield",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "Lower the pass-through assumption if promotions or discounting return.",
                "whyItMatters": "Yield erosion turns a fuel-cost shock into a revenue-quality problem.",
                "polarity": "negative",
                "x": 710,
                "y": 190,
            },
            {
                "id": "load-factor-risk",
                "label": "Load-factor risk",
                "subtitle": "Seats fly with weaker utilization",
                "driver": "Load factors",
                "evidenceType": "Data",
                "confidence": "Medium",
                "researchImplication": "Track whether lower bookings show up as lower utilization or only lower fares.",
                "whyItMatters": "Lower load factors spread fixed costs across fewer passengers and hit unit economics.",
                "polarity": "risk",
                "x": 340,
                "y": 340,
            },
            {
                "id": "operating-leverage",
                "label": "Operating leverage",
                "subtitle": "Fixed costs amplify volume misses",
                "driver": "Operating leverage",
                "evidenceType": "Framework inference",
                "confidence": "Medium/High",
                "researchImplication": "Small demand misses can create nonlinear margin downside.",
                "whyItMatters": "Aircraft, labor, airport, and maintenance costs limit how quickly airlines can resize supply.",
                "polarity": "risk",
                "x": 710,
                "y": 340,
            },
            {
                "id": "capacity-discipline",
                "label": "Capacity discipline",
                "subtitle": "Schedules adjust to protect fares",
                "driver": "Capacity discipline",
                "evidenceType": "Open question",
                "confidence": "Medium",
                "researchImplication": "The constructive case requires carriers to cut capacity before pricing breaks.",
                "whyItMatters": "Disciplined capacity can protect yield, but aggressive cuts can also cap revenue growth.",
                "polarity": "mixed",
                "x": 340,
                "y": 500,
            },
            {
                "id": "hedging-buffer",
                "label": "Hedging buffer",
                "subtitle": "Coverage delays fuel exposure",
                "driver": "Hedging coverage",
                "evidenceType": "Open question",
                "confidence": "Low/Medium",
                "researchImplication": "Carrier-level hedge coverage can create near-term dispersion.",
                "whyItMatters": "Hedges can soften the immediate cost shock but rarely remove the underlying margin issue.",
                "polarity": "mixed",
                "x": 340,
                "y": 650,
            },
            {
                "id": "margin-cash-flow",
                "label": "Margin / cash flow",
                "subtitle": "Terminal operating judgment",
                "driver": "Margin / free cash flow",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "The final judgment depends on whether fare yields and capacity discipline offset fuel inflation.",
                "whyItMatters": "Margin and free-cash-flow resilience determine balance-sheet flexibility through the shock.",
                "polarity": "mixed",
                "x": 710,
                "y": 560,
            },
        ],
        "transmissionEdges": [
            {
                "id": "e1",
                "source": "oil-price-shock",
                "target": "jet-fuel-cost",
                "label": "raises input cost",
                "polarity": "negative",
            },
            {
                "id": "e2",
                "source": "jet-fuel-cost",
                "target": "unit-cost-pressure",
                "label": "lifts CASM",
                "polarity": "negative",
            },
            {
                "id": "e3",
                "source": "oil-price-shock",
                "target": "fare-elasticity",
                "label": "requires pass-through",
                "polarity": "risk",
            },
            {
                "id": "e4",
                "source": "fare-elasticity",
                "target": "yield-pressure",
                "label": "limits repricing",
                "polarity": "negative",
            },
            {
                "id": "e5",
                "source": "weak-demand",
                "target": "fare-elasticity",
                "label": "weakens pricing",
                "polarity": "risk",
            },
            {
                "id": "e6",
                "source": "weak-demand",
                "target": "load-factor-risk",
                "label": "slows bookings",
                "polarity": "risk",
            },
            {
                "id": "e7",
                "source": "load-factor-risk",
                "target": "operating-leverage",
                "label": "amplifies costs",
                "polarity": "risk",
            },
            {
                "id": "e8",
                "source": "capacity-discipline",
                "target": "yield-pressure",
                "label": "can support fares",
                "polarity": "mixed",
            },
            {
                "id": "e9",
                "source": "weak-demand",
                "target": "capacity-discipline",
                "label": "forces schedule choice",
                "polarity": "mixed",
            },
            {
                "id": "e10",
                "source": "hedging-buffer",
                "target": "margin-cash-flow",
                "label": "delays cost hit",
                "polarity": "mixed",
            },
            {
                "id": "e11",
                "source": "unit-cost-pressure",
                "target": "margin-cash-flow",
                "label": "compresses margin",
                "polarity": "negative",
            },
            {
                "id": "e12",
                "source": "yield-pressure",
                "target": "margin-cash-flow",
                "label": "reduces revenue offset",
                "polarity": "negative",
            },
            {
                "id": "e13",
                "source": "operating-leverage",
                "target": "margin-cash-flow",
                "label": "magnifies downside",
                "polarity": "risk",
            },
        ],
        "charts": [
            {
                "title": "Oil shock index",
                "subtitle": "Illustrative crude and jet-fuel move",
                "unit": "idx",
                "tone": "amber",
                "data": [
                    {"period": "Q1", "value": 100},
                    {"period": "Q2", "value": 108},
                    {"period": "Q3", "value": 116},
                    {"period": "Q4", "value": 123},
                    {"period": "Q5", "value": 125},
                ],
            },
            {
                "title": "Fare pass-through",
                "subtitle": "Fuel cost versus fare yield",
                "unit": "idx",
                "tone": "cyan",
                "data": [
                    {"period": "Q1", "value": 100, "comparison": 100},
                    {"period": "Q2", "value": 104, "comparison": 108},
                    {"period": "Q3", "value": 106, "comparison": 116},
                    {"period": "Q4", "value": 105, "comparison": 123},
                    {"period": "Q5", "value": 104, "comparison": 125},
                ],
            },
            {
                "title": "Travel demand proxy",
                "subtitle": "Leisure booking sensitivity",
                "unit": "idx",
                "tone": "rose",
                "data": [
                    {"period": "Q1", "value": 100},
                    {"period": "Q2", "value": 97},
                    {"period": "Q3", "value": 94},
                    {"period": "Q4", "value": 91},
                    {"period": "Q5", "value": 90},
                ],
            },
            {
                "title": "Margin bridge",
                "subtitle": "Capacity discipline versus cost pressure",
                "unit": "%",
                "tone": "emerald",
                "data": [
                    {"period": "Q1", "value": 12.5, "comparison": 12.5},
                    {"period": "Q2", "value": 11.2, "comparison": 12.0},
                    {"period": "Q3", "value": 9.6, "comparison": 11.3},
                    {"period": "Q4", "value": 8.8, "comparison": 10.8},
                    {"period": "Q5", "value": 9.1, "comparison": 10.5},
                ],
            },
        ],
        "evidence": [
            {
                "claim": "Higher oil prices flow into airline fuel expense and pressure unit costs.",
                "type": "Framework inference",
                "confidence": "High",
                "importance": "High",
                "driver": "Jet fuel cost",
                "sourceLabel": "Airline sector driver map",
                "sourceType": "Internal framework",
                "sourceQuality": "Medium",
            },
            {
                "claim": "Weak consumer demand reduces the fare pass-through available to offset fuel inflation.",
                "type": "Framework inference",
                "confidence": "Medium/High",
                "importance": "High",
                "driver": "Fare elasticity",
                "sourceLabel": "Demand elasticity framework",
                "sourceType": "Framework",
                "sourceQuality": "Medium",
            },
            {
                "claim": "Load-factor deterioration can amplify revenue misses because airline cost bases are partly fixed over short horizons.",
                "type": "Data",
                "confidence": "Medium",
                "importance": "High",
                "driver": "Operating leverage",
                "sourceLabel": "Future airline KPI pack",
                "sourceType": "Data placeholder",
                "sourceQuality": "High",
            },
            {
                "claim": "Capacity discipline is the main management lever that can protect yield in a weaker demand environment.",
                "type": "Framework inference",
                "confidence": "Medium",
                "importance": "High",
                "driver": "Capacity discipline",
                "sourceLabel": "Industry-cycle framework",
                "sourceType": "Internal framework",
                "sourceQuality": "Medium",
            },
            {
                "claim": "Hedging coverage can create near-term carrier dispersion but does not remove the underlying demand and margin test.",
                "type": "Open question",
                "confidence": "Low/Medium",
                "importance": "Medium",
                "driver": "Hedging coverage",
                "sourceLabel": "Carrier-level diligence list",
                "sourceType": "Open research item",
                "sourceQuality": "Medium",
            },
            {
                "claim": "The central unresolved issue is whether airlines defend market share with capacity or defend margins with schedule cuts.",
                "type": "Open question",
                "confidence": "Medium",
                "importance": "High",
                "driver": "Capacity discipline",
                "sourceLabel": "Skeptic agent issue list",
                "sourceType": "Open research item",
                "sourceQuality": "Medium",
            },
        ],
        "bullCase": {
            "title": "Constructive transmission",
            "points": [
                "Premium and corporate demand hold up better than price-sensitive leisure demand.",
                "Carriers reduce capacity early enough to protect fare yields and load factors.",
                "Fuel hedges and fleet efficiency delay the full cost shock for stronger operators.",
                "Balance sheets remain flexible if free cash flow stays positive through the shock.",
            ],
        },
        "bearCase": {
            "title": "Adverse transmission",
            "points": [
                "Fuel costs rise faster than fares because weak consumers resist higher ticket prices.",
                "Discounting returns as airlines try to fill seats, pushing yields and load factors lower.",
                "Operating leverage turns modest volume weakness into material margin compression.",
                "Leverage and liquidity concerns reappear if free cash flow weakens for multiple quarters.",
            ],
        },
        "memo": [
            {
                "title": "Bottom line",
                "body": "An oil shock is most damaging for airlines when demand is weakening at the same time. Fuel inflation raises the cost base, while softer consumers limit fare pass-through and increase load-factor risk.",
            },
            {
                "title": "Most important driver",
                "body": "The decisive branch is capacity discipline. If airlines cut schedules quickly, yield and utilization can hold up. If carriers defend share with too much capacity, fare pressure and fixed-cost absorption can turn the shock into a margin and cash-flow problem.",
            },
            {
                "title": "Evidence standard",
                "body": "This prototype uses placeholder series and framework labels only. It does not use live commodity prices, airline filings, passenger data, recommendations, or price targets.",
            },
        ],
        "openQuestions": [
            {
                "question": "Can airlines pass fuel inflation through to fares without damaging load factors?",
                "whyItMatters": "This determines whether higher oil prices hit margins directly or are partly absorbed by pricing.",
                "owner": "Pricing and booking follow-up",
            },
            {
                "question": "Will carriers cut capacity early or defend market share into weaker demand?",
                "whyItMatters": "Capacity discipline is the main lever for protecting yields and utilization.",
                "owner": "Industry supply follow-up",
            },
            {
                "question": "How much hedge coverage and liquidity protection exists by carrier?",
                "whyItMatters": "Hedges, cash, and leverage create large dispersion across airlines in the same macro shock.",
                "owner": "Carrier diligence",
            },
        ],
    }
)

__all__ = ["OIL_AIRLINES_RESEARCH_RUN"]
