from app.schemas import ResearchRun


DEMO_RESEARCH_RUN = ResearchRun.model_validate(
    {
        "question": "How would rate cuts affect Canadian banks?",
        "classification": "macro_to_sector_shock",
        "timestamp": "Prototype run | hardcoded backend data",
        "scenario": "Bank of Canada easing cycle",
        "headline": "Rate cuts improve credit relief, but bank earnings depend on deposit beta, mortgage renewal timing, and asset sensitivity.",
        "thesis": "The Canadian-bank rate-cut setup is analytically mixed. Lower rates can ease household debt-service stress and eventually support loan growth, but near-term net interest income depends on how quickly assets reprice versus deposits, while housing exposure and unemployment determine whether provisions actually normalize.",
        "judgment": {
            "title": "Research judgment",
            "stance": "Balanced, credit-sensitive, not mechanically bullish",
            "summary": "Treat rate cuts as a transmission question rather than a one-factor catalyst. The constructive case requires contained unemployment, orderly mortgage renewals, falling credit losses, and enough deposit beta to protect NII. The adverse case is a recessionary easing cycle where provisions and ROE compression overwhelm multiple support.",
            "watchItems": [
                "Deposit beta and funding-cost lag",
                "Mortgage renewal shock absorption",
                "Provision build versus credit-loss peaking",
                "ROE path and valuation multiple discipline",
            ],
        },
        "keyDrivers": [
            "Deposit beta",
            "Mortgage renewals",
            "Asset sensitivity",
            "Net interest income",
            "Provisions",
            "Credit losses",
            "Housing exposure",
            "ROE / valuation multiple",
        ],
        "metrics": [
            {
                "label": "Policy shock",
                "value": "-100 bps",
                "detail": "Illustrative 12-month easing path",
                "tone": "cyan",
            },
            {
                "label": "Credit impulse",
                "value": "Conditional",
                "detail": "Depends on renewals, unemployment, and housing stress",
                "tone": "emerald",
            },
            {
                "label": "NII sensitivity",
                "value": "Asset-led",
                "detail": "Asset repricing can pressure NII before deposit beta helps",
                "tone": "amber",
            },
            {
                "label": "Skeptic flag",
                "value": "Provision risk",
                "detail": "Recessionary cuts can lift PCLs and compress ROE",
                "tone": "rose",
            },
        ],
        "agents": [
            {
                "name": "Planner Agent",
                "role": "Classifies the question and extracts the sector driver map.",
                "status": "complete",
                "duration": "00:06",
                "output": [
                    "Research type: macro_to_sector_shock",
                    "Shock: rate cuts",
                    "Affected sector: Canadian banks",
                    "Drivers: deposit beta, mortgage renewals, asset sensitivity, provisions, ROE / valuation",
                ],
            },
            {
                "name": "Data Agent",
                "role": "Stages macro and banking indicators for the demo run.",
                "status": "complete",
                "duration": "00:09",
                "output": [
                    "Policy-rate path staged",
                    "Deposit beta, mortgage-renewal, and credit-loss placeholders attached",
                    "No live FRED or market-data calls in Milestone 2",
                ],
            },
            {
                "name": "Framework Agent",
                "role": "Selects the analytical lens for the transmission chain.",
                "status": "complete",
                "duration": "00:07",
                "output": [
                    "Framework: monetary transmission + credit cycle",
                    "Primary tension: NII pressure versus provision relief and valuation support",
                ],
            },
            {
                "name": "Skeptic Agent",
                "role": "Challenges the clean bullish interpretation.",
                "status": "complete",
                "duration": "00:05",
                "output": [
                    "Cuts can signal weakening growth",
                    "Housing exposure and unemployment can dominate the rate effect",
                    "Deposit beta assumptions are uncertain",
                ],
            },
            {
                "name": "Synthesis Agent",
                "role": "Produces the map, evidence board, bull/bear view, and memo.",
                "status": "complete",
                "duration": "00:08",
                "output": [
                    "Transmission map assembled",
                    "Claims labeled by evidence type",
                    "Memo avoids recommendations and price targets",
                ],
            },
        ],
        "transmissionNodes": [
            {
                "id": "rate-cuts",
                "label": "Rate cuts",
                "subtitle": "BoC policy-rate easing path",
                "driver": "Policy shock",
                "evidenceType": "Framework inference",
                "confidence": "High",
                "researchImplication": "Start with balance-sheet sensitivity, not a generic lower-rates-equals-bullish assumption.",
                "whyItMatters": "Canadian banks react differently depending on asset duration, deposit mix, mortgage exposure, and credit quality.",
                "polarity": "neutral",
                "x": 0,
                "y": 250,
            },
            {
                "id": "asset-repricing",
                "label": "Asset-yield repricing",
                "subtitle": "Floating-rate assets reset lower",
                "driver": "Asset sensitivity",
                "evidenceType": "Framework inference",
                "confidence": "Medium/High",
                "researchImplication": "Near-term NII can fall if loans and securities reprice faster than deposit costs.",
                "whyItMatters": "Asset-sensitive banks tend to lose some earnings leverage when policy rates decline.",
                "polarity": "negative",
                "x": 340,
                "y": 45,
            },
            {
                "id": "nii-pressure",
                "label": "NII / margin pressure",
                "subtitle": "Spread income can soften",
                "driver": "Net interest income",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "Model the first-order earnings drag before assuming lower credit costs offset it.",
                "whyItMatters": "Net interest income is a core Canadian-bank earnings line and can drive early estimate revisions.",
                "polarity": "negative",
                "x": 710,
                "y": 45,
            },
            {
                "id": "deposit-beta",
                "label": "Deposit beta benefit",
                "subtitle": "Funding costs may lag lower",
                "driver": "Deposit beta",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "A faster fall in deposit costs can partly cushion the NII drag from asset repricing.",
                "whyItMatters": "Deposit pricing discipline separates stronger funding franchises from more rate-sensitive balance sheets.",
                "polarity": "mixed",
                "x": 340,
                "y": 155,
            },
            {
                "id": "mortgage-renewals",
                "label": "Mortgage renewal relief",
                "subtitle": "Payment shock can moderate",
                "driver": "Mortgage renewals",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "Lower renewal rates reduce borrower stress but do not immediately remove housing-cycle risk.",
                "whyItMatters": "Canadian mortgage renewals are a major channel between policy rates, household cash flow, and bank credit quality.",
                "polarity": "positive",
                "x": 340,
                "y": 265,
            },
            {
                "id": "credit-losses",
                "label": "Credit-loss trajectory",
                "subtitle": "Delinquencies may peak lower",
                "driver": "Credit losses",
                "evidenceType": "Data",
                "confidence": "Medium",
                "researchImplication": "Provision assumptions should improve only if labor and housing indicators confirm the relief path.",
                "whyItMatters": "Credit losses and provisions can overwhelm modest NII changes in a downturn.",
                "polarity": "positive",
                "x": 710,
                "y": 265,
            },
            {
                "id": "loan-demand",
                "label": "Loan-growth impulse",
                "subtitle": "Volumes recover with a lag",
                "driver": "Loan growth",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "Volume upside is a second-order benefit and likely lags the initial margin and credit signals.",
                "whyItMatters": "A cleaner loan-growth path supports revenue durability but needs demand, underwriting, and capital discipline.",
                "polarity": "positive",
                "x": 710,
                "y": 375,
            },
            {
                "id": "housing-exposure",
                "label": "Housing exposure test",
                "subtitle": "Collateral and borrower stress",
                "driver": "Housing exposure",
                "evidenceType": "Open question",
                "confidence": "Medium",
                "researchImplication": "The easing case is fragile if home prices, unemployment, or consumer delinquencies deteriorate.",
                "whyItMatters": "Housing is the key Canadian-bank macro sensitivity that can turn rate cuts into a credit-risk signal.",
                "polarity": "risk",
                "x": 340,
                "y": 485,
            },
            {
                "id": "provisions",
                "label": "Provision path",
                "subtitle": "PCL build or release",
                "driver": "Provisions",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "The bull case needs provisions to stabilize; the bear case assumes recessionary cuts keep PCLs elevated.",
                "whyItMatters": "Provision expense directly hits earnings, ROE, and investor confidence in book-value quality.",
                "polarity": "risk",
                "x": 710,
                "y": 485,
            },
            {
                "id": "discount-rates",
                "label": "Lower discount rates",
                "subtitle": "Equity multiple support",
                "driver": "Valuation",
                "evidenceType": "Framework inference",
                "confidence": "Medium",
                "researchImplication": "Lower discount rates can support bank multiples only if earnings risk is not being revised down faster.",
                "whyItMatters": "Multiple expansion is conditional; it should not be treated as a standalone investment conclusion.",
                "polarity": "positive",
                "x": 340,
                "y": 625,
            },
            {
                "id": "roe-valuation",
                "label": "ROE / valuation multiple",
                "subtitle": "Terminal market judgment",
                "driver": "ROE / valuation multiple",
                "evidenceType": "Framework inference",
                "confidence": "Low/Medium",
                "researchImplication": "The final judgment is whether lower credit risk and multiple support offset NII and provision pressure.",
                "whyItMatters": "ROE durability is the bridge between macro easing and how investors may value Canadian bank earnings.",
                "polarity": "mixed",
                "x": 710,
                "y": 625,
            },
            {
                "id": "recession-risk",
                "label": "Recession signal risk",
                "subtitle": "Cuts may reflect weak growth",
                "driver": "Macro regime",
                "evidenceType": "Open question",
                "confidence": "Medium",
                "researchImplication": "Separate benign disinflation cuts from defensive recession cuts before making the sector call.",
                "whyItMatters": "A recessionary easing cycle usually raises credit costs and lowers earnings visibility.",
                "polarity": "risk",
                "x": 0,
                "y": 500,
            },
        ],
        "transmissionEdges": [
            {
                "id": "e1",
                "source": "rate-cuts",
                "target": "asset-repricing",
                "label": "lowers yields",
                "polarity": "negative",
            },
            {
                "id": "e2",
                "source": "asset-repricing",
                "target": "nii-pressure",
                "label": "pressures spread income",
                "polarity": "negative",
            },
            {
                "id": "e3",
                "source": "rate-cuts",
                "target": "deposit-beta",
                "label": "reprices funding",
                "polarity": "mixed",
            },
            {
                "id": "e4",
                "source": "rate-cuts",
                "target": "mortgage-renewals",
                "label": "eases payment reset",
                "polarity": "positive",
            },
            {
                "id": "e5",
                "source": "mortgage-renewals",
                "target": "credit-losses",
                "label": "can reduce stress",
                "polarity": "positive",
            },
            {
                "id": "e6",
                "source": "credit-losses",
                "target": "loan-demand",
                "label": "improves risk appetite",
                "polarity": "positive",
            },
            {
                "id": "e7",
                "source": "rate-cuts",
                "target": "housing-exposure",
                "label": "tests collateral risk",
                "polarity": "risk",
            },
            {
                "id": "e8",
                "source": "housing-exposure",
                "target": "provisions",
                "label": "drives PCL risk",
                "polarity": "risk",
            },
            {
                "id": "e9",
                "source": "rate-cuts",
                "target": "discount-rates",
                "label": "lowers discount rate",
                "polarity": "positive",
            },
            {
                "id": "e10",
                "source": "discount-rates",
                "target": "roe-valuation",
                "label": "supports multiple",
                "polarity": "mixed",
            },
            {
                "id": "e11",
                "source": "nii-pressure",
                "target": "roe-valuation",
                "label": "weighs on ROE",
                "polarity": "negative",
            },
            {
                "id": "e12",
                "source": "provisions",
                "target": "roe-valuation",
                "label": "changes earnings quality",
                "polarity": "risk",
            },
            {
                "id": "e13",
                "source": "rate-cuts",
                "target": "recession-risk",
                "label": "may signal",
                "polarity": "risk",
            },
            {
                "id": "e14",
                "source": "recession-risk",
                "target": "provisions",
                "label": "raises loss reserves",
                "polarity": "risk",
            },
        ],
        "charts": [
            {
                "title": "Policy rate path",
                "subtitle": "Illustrative easing cycle",
                "unit": "%",
                "tone": "cyan",
                "data": [
                    {"period": "Q1", "value": 5.0},
                    {"period": "Q2", "value": 4.75},
                    {"period": "Q3", "value": 4.25},
                    {"period": "Q4", "value": 4.0},
                    {"period": "Q5", "value": 3.75},
                ],
            },
            {
                "title": "NII sensitivity index",
                "subtitle": "Asset repricing versus deposit beta",
                "unit": "idx",
                "tone": "amber",
                "data": [
                    {"period": "Q1", "value": 100, "comparison": 100},
                    {"period": "Q2", "value": 97, "comparison": 101},
                    {"period": "Q3", "value": 95, "comparison": 100},
                    {"period": "Q4", "value": 96, "comparison": 99},
                    {"period": "Q5", "value": 98, "comparison": 99},
                ],
            },
            {
                "title": "Mortgage renewal stress",
                "subtitle": "Payment-shock relief path",
                "unit": "%",
                "tone": "emerald",
                "data": [
                    {"period": "Q1", "value": 7.8},
                    {"period": "Q2", "value": 7.2},
                    {"period": "Q3", "value": 6.5},
                    {"period": "Q4", "value": 5.9},
                    {"period": "Q5", "value": 5.4},
                ],
            },
            {
                "title": "Provision risk proxy",
                "subtitle": "Watch PCLs and unemployment",
                "unit": "idx",
                "tone": "rose",
                "data": [
                    {"period": "Q1", "value": 68},
                    {"period": "Q2", "value": 72},
                    {"period": "Q3", "value": 70},
                    {"period": "Q4", "value": 65},
                    {"period": "Q5", "value": 60},
                ],
            },
        ],
        "evidence": [
            {
                "claim": "Rate cuts can pressure net interest income when asset yields reprice faster than deposit costs.",
                "type": "Framework inference",
                "confidence": "Medium",
                "importance": "High",
                "driver": "Net interest income",
                "sourceLabel": "Bank sector driver map",
                "sourceType": "Internal framework",
                "sourceQuality": "Medium",
            },
            {
                "claim": "Deposit beta determines how much funding-cost relief offsets asset-yield compression.",
                "type": "Framework inference",
                "confidence": "Medium/High",
                "importance": "High",
                "driver": "Deposit beta",
                "sourceLabel": "Bank ALM logic",
                "sourceType": "Framework",
                "sourceQuality": "Medium",
            },
            {
                "claim": "Mortgage renewal stress is a central Canadian-bank channel between policy rates and household credit quality.",
                "type": "Framework inference",
                "confidence": "Medium",
                "importance": "High",
                "driver": "Mortgage renewals",
                "sourceLabel": "Canadian bank exposure map",
                "sourceType": "Sector model placeholder",
                "sourceQuality": "Medium",
            },
            {
                "claim": "Credit outcomes depend heavily on unemployment, housing exposure, and refinancing stress.",
                "type": "Data",
                "confidence": "High",
                "importance": "High",
                "driver": "Credit losses",
                "sourceLabel": "Future macro + bank KPI pack",
                "sourceType": "Data placeholder",
                "sourceQuality": "High",
            },
            {
                "claim": "Provision expense is the swing factor that can turn rate-cut relief into ROE pressure.",
                "type": "Framework inference",
                "confidence": "Medium",
                "importance": "High",
                "driver": "Provisions",
                "sourceLabel": "Credit cycle framework",
                "sourceType": "Internal framework",
                "sourceQuality": "Medium",
            },
            {
                "claim": "Investors may reward lower discount rates only if NII and provision revisions remain contained.",
                "type": "Narrative signal",
                "confidence": "Low/Medium",
                "importance": "Medium",
                "driver": "ROE / valuation multiple",
                "sourceLabel": "Market narrative placeholder",
                "sourceType": "Narrative signal",
                "sourceQuality": "Low",
            },
            {
                "claim": "The central unresolved issue is whether cuts reflect normalization or recession risk.",
                "type": "Open question",
                "confidence": "Medium",
                "importance": "High",
                "driver": "Macro regime",
                "sourceLabel": "Skeptic agent issue list",
                "sourceType": "Open research item",
                "sourceQuality": "Medium",
            },
        ],
        "bullCase": {
            "title": "Constructive transmission",
            "points": [
                "Deposit beta protects funding costs enough to limit NII compression.",
                "Lower renewal rates relieve household cash-flow pressure and slow credit-loss migration.",
                "Provision builds peak earlier if unemployment and housing collateral remain orderly.",
                "ROE durability plus lower discount rates can support valuation multiples without implying a recommendation.",
            ],
        },
        "bearCase": {
            "title": "Adverse transmission",
            "points": [
                "Initial rate cuts may be a signal that growth and labor conditions are deteriorating.",
                "Asset-yield repricing pressures NII before deposit-cost benefits fully appear.",
                "Mortgage renewals and housing exposure keep the credit-loss path highly sensitive.",
                "Higher provisions compress ROE and can offset any lower-rate multiple support.",
            ],
        },
        "memo": [
            {
                "title": "Bottom line",
                "body": "Rate cuts are not mechanically bullish for Canadian banks. The demo view is balanced: easing can reduce mortgage-renewal stress and eventually support credit outcomes, but first-order earnings pressure may appear through asset-yield repricing, NII sensitivity, and still-elevated provisions.",
            },
            {
                "title": "Most important driver",
                "body": "The decisive branch is whether cuts are benign normalization or recessionary easing. If employment, housing, and delinquencies hold, credit-loss and valuation branches improve. If cuts arrive because growth is rolling over, provisions and ROE pressure can dominate deposit-beta and discount-rate benefits.",
            },
            {
                "title": "Evidence standard",
                "body": "This prototype labels claims as data, framework inference, narrative signal, or open question and now includes source-readiness fields. It does not present price targets, buy/sell calls, live data, or unsupported company-specific conclusions.",
            },
        ],
        "openQuestions": [
            {
                "question": "Are cuts driven by disinflation normalization or by a deteriorating labor market?",
                "whyItMatters": "This determines whether credit relief or provision risk dominates.",
                "owner": "Macro data follow-up",
            },
            {
                "question": "How quickly do Canadian bank assets and deposits reprice under this scenario?",
                "whyItMatters": "Deposit beta, asset sensitivity, and mortgage renewal timing shape the NII path.",
                "owner": "Bank model follow-up",
            },
            {
                "question": "Which loan books are most exposed to household refinancing stress?",
                "whyItMatters": "Housing exposure and consumer-credit sensitivity can change the provision and ROE balance.",
                "owner": "Sector diligence",
            },
        ],
    }
)
