from pydantic import BaseModel

from app.agents.data_agent import DataAgentOutput
from app.agents.planner import PlannerOutput
from app.schemas import AgentStage, EvidenceItem, TransmissionEdge, TransmissionNode


class FrameworkAgentOutput(BaseModel):
    transmissionNodes: list[TransmissionNode]
    transmissionEdges: list[TransmissionEdge]
    evidence: list[EvidenceItem]
    stage: AgentStage


def run_framework_agent(
    _: PlannerOutput, __: DataAgentOutput
) -> FrameworkAgentOutput:
    return FrameworkAgentOutput.model_validate(
        {
            "transmissionNodes": [
                {
                    "id": "rate-cuts",
                    "label": "Rate cuts",
                    "subtitle": "BoC policy-rate easing path",
                    "driver": "Policy shock",
                    "evidenceType": "Framework inference",
                    "confidence": "High",
                    "researchImplication": "Start with balance-sheet sensitivity, not a generic lower-rates-equals-bullish assumption.",
                    "whyItMatters": "Canadian banks react differently depending on asset duration, deposit mix, mortgage exposure, and credit quality.",
                    "polarity": "neutral",
                    "x": 0,
                    "y": 250,
                },
                {
                    "id": "asset-repricing",
                    "label": "Asset-yield repricing",
                    "subtitle": "Floating-rate assets reset lower",
                    "driver": "Asset sensitivity",
                    "evidenceType": "Framework inference",
                    "confidence": "Medium/High",
                    "researchImplication": "Near-term NII can fall if loans and securities reprice faster than deposit costs.",
                    "whyItMatters": "Asset-sensitive banks tend to lose some earnings leverage when policy rates decline.",
                    "polarity": "negative",
                    "x": 340,
                    "y": 45,
                },
                {
                    "id": "nii-pressure",
                    "label": "NII / margin pressure",
                    "subtitle": "Spread income can soften",
                    "driver": "Net interest income",
                    "evidenceType": "Framework inference",
                    "confidence": "Medium",
                    "researchImplication": "Model the first-order earnings drag before assuming lower credit costs offset it.",
                    "whyItMatters": "Net interest income is a core Canadian-bank earnings line and can drive early estimate revisions.",
                    "polarity": "negative",
                    "x": 710,
                    "y": 45,
                },
                {
                    "id": "deposit-beta",
                    "label": "Deposit beta benefit",
                    "subtitle": "Funding costs may lag lower",
                    "driver": "Deposit beta",
                    "evidenceType": "Framework inference",
                    "confidence": "Medium",
                    "researchImplication": "A faster fall in deposit costs can partly cushion the NII drag from asset repricing.",
                    "whyItMatters": "Deposit pricing discipline separates stronger funding franchises from more rate-sensitive balance sheets.",
                    "polarity": "mixed",
                    "x": 340,
                    "y": 155,
                },
                {
                    "id": "mortgage-renewals",
                    "label": "Mortgage renewal relief",
                    "subtitle": "Payment shock can moderate",
                    "driver": "Mortgage renewals",
                    "evidenceType": "Framework inference",
                    "confidence": "Medium",
                    "researchImplication": "Lower renewal rates reduce borrower stress but do not immediately remove housing-cycle risk.",
                    "whyItMatters": "Canadian mortgage renewals are a major channel between policy rates, household cash flow, and bank credit quality.",
                    "polarity": "positive",
                    "x": 340,
                    "y": 265,
                },
                {
                    "id": "credit-losses",
                    "label": "Credit-loss trajectory",
                    "subtitle": "Delinquencies may peak lower",
                    "driver": "Credit losses",
                    "evidenceType": "Data",
                    "confidence": "Medium",
                    "researchImplication": "Provision assumptions should improve only if labor and housing indicators confirm the relief path.",
                    "whyItMatters": "Credit losses and provisions can overwhelm modest NII changes in a downturn.",
                    "polarity": "positive",
                    "x": 710,
                    "y": 265,
                },
                {
                    "id": "loan-demand",
                    "label": "Loan-growth impulse",
                    "subtitle": "Volumes recover with a lag",
                    "driver": "Loan growth",
                    "evidenceType": "Framework inference",
                    "confidence": "Medium",
                    "researchImplication": "Volume upside is a second-order benefit and likely lags the initial margin and credit signals.",
                    "whyItMatters": "A cleaner loan-growth path supports revenue durability but needs demand, underwriting, and capital discipline.",
                    "polarity": "positive",
                    "x": 710,
                    "y": 375,
                },
                {
                    "id": "housing-exposure",
                    "label": "Housing exposure test",
                    "subtitle": "Collateral and borrower stress",
                    "driver": "Housing exposure",
                    "evidenceType": "Open question",
                    "confidence": "Medium",
                    "researchImplication": "The easing case is fragile if home prices, unemployment, or consumer delinquencies deteriorate.",
                    "whyItMatters": "Housing is the key Canadian-bank macro sensitivity that can turn rate cuts into a credit-risk signal.",
                    "polarity": "risk",
                    "x": 340,
                    "y": 485,
                },
                {
                    "id": "provisions",
                    "label": "Provision path",
                    "subtitle": "PCL build or release",
                    "driver": "Provisions",
                    "evidenceType": "Framework inference",
                    "confidence": "Medium",
                    "researchImplication": "The bull case needs provisions to stabilize; the bear case assumes recessionary cuts keep PCLs elevated.",
                    "whyItMatters": "Provision expense directly hits earnings, ROE, and investor confidence in book-value quality.",
                    "polarity": "risk",
                    "x": 710,
                    "y": 485,
                },
                {
                    "id": "discount-rates",
                    "label": "Lower discount rates",
                    "subtitle": "Equity multiple support",
                    "driver": "Valuation",
                    "evidenceType": "Framework inference",
                    "confidence": "Medium",
                    "researchImplication": "Lower discount rates can support bank multiples only if earnings risk is not being revised down faster.",
                    "whyItMatters": "Multiple expansion is conditional; it should not be treated as a standalone investment conclusion.",
                    "polarity": "positive",
                    "x": 340,
                    "y": 625,
                },
                {
                    "id": "roe-valuation",
                    "label": "ROE / valuation multiple",
                    "subtitle": "Terminal market judgment",
                    "driver": "ROE / valuation multiple",
                    "evidenceType": "Framework inference",
                    "confidence": "Low/Medium",
                    "researchImplication": "The final judgment is whether lower credit risk and multiple support offset NII and provision pressure.",
                    "whyItMatters": "ROE durability is the bridge between macro easing and how investors may value Canadian bank earnings.",
                    "polarity": "mixed",
                    "x": 710,
                    "y": 625,
                },
                {
                    "id": "recession-risk",
                    "label": "Recession signal risk",
                    "subtitle": "Cuts may reflect weak growth",
                    "driver": "Macro regime",
                    "evidenceType": "Open question",
                    "confidence": "Medium",
                    "researchImplication": "Separate benign disinflation cuts from defensive recession cuts before making the sector call.",
                    "whyItMatters": "A recessionary easing cycle usually raises credit costs and lowers earnings visibility.",
                    "polarity": "risk",
                    "x": 0,
                    "y": 500,
                },
            ],
            "transmissionEdges": [
                {
                    "id": "e1",
                    "source": "rate-cuts",
                    "target": "asset-repricing",
                    "label": "lowers yields",
                    "polarity": "negative",
                },
                {
                    "id": "e2",
                    "source": "asset-repricing",
                    "target": "nii-pressure",
                    "label": "pressures spread income",
                    "polarity": "negative",
                },
                {
                    "id": "e3",
                    "source": "rate-cuts",
                    "target": "deposit-beta",
                    "label": "reprices funding",
                    "polarity": "mixed",
                },
                {
                    "id": "e4",
                    "source": "rate-cuts",
                    "target": "mortgage-renewals",
                    "label": "eases payment reset",
                    "polarity": "positive",
                },
                {
                    "id": "e5",
                    "source": "mortgage-renewals",
                    "target": "credit-losses",
                    "label": "can reduce stress",
                    "polarity": "positive",
                },
                {
                    "id": "e6",
                    "source": "credit-losses",
                    "target": "loan-demand",
                    "label": "improves risk appetite",
                    "polarity": "positive",
                },
                {
                    "id": "e7",
                    "source": "rate-cuts",
                    "target": "housing-exposure",
                    "label": "tests collateral risk",
                    "polarity": "risk",
                },
                {
                    "id": "e8",
                    "source": "housing-exposure",
                    "target": "provisions",
                    "label": "drives PCL risk",
                    "polarity": "risk",
                },
                {
                    "id": "e9",
                    "source": "rate-cuts",
                    "target": "discount-rates",
                    "label": "lowers discount rate",
                    "polarity": "positive",
                },
                {
                    "id": "e10",
                    "source": "discount-rates",
                    "target": "roe-valuation",
                    "label": "supports multiple",
                    "polarity": "mixed",
                },
                {
                    "id": "e11",
                    "source": "nii-pressure",
                    "target": "roe-valuation",
                    "label": "weighs on ROE",
                    "polarity": "negative",
                },
                {
                    "id": "e12",
                    "source": "provisions",
                    "target": "roe-valuation",
                    "label": "changes earnings quality",
                    "polarity": "risk",
                },
                {
                    "id": "e13",
                    "source": "rate-cuts",
                    "target": "recession-risk",
                    "label": "may signal",
                    "polarity": "risk",
                },
                {
                    "id": "e14",
                    "source": "recession-risk",
                    "target": "provisions",
                    "label": "raises loss reserves",
                    "polarity": "risk",
                },
            ],
            "evidence": [
                {
                    "claim": "Rate cuts can pressure net interest income when asset yields reprice faster than deposit costs.",
                    "type": "Framework inference",
                    "confidence": "Medium",
                    "importance": "High",
                    "driver": "Net interest income",
                    "sourceLabel": "Bank sector driver map",
                    "sourceType": "Internal framework",
                    "sourceQuality": "Medium",
                },
                {
                    "claim": "Deposit beta determines how much funding-cost relief offsets asset-yield compression.",
                    "type": "Framework inference",
                    "confidence": "Medium/High",
                    "importance": "High",
                    "driver": "Deposit beta",
                    "sourceLabel": "Bank ALM logic",
                    "sourceType": "Framework",
                    "sourceQuality": "Medium",
                },
                {
                    "claim": "Mortgage renewal stress is a central Canadian-bank channel between policy rates and household credit quality.",
                    "type": "Framework inference",
                    "confidence": "Medium",
                    "importance": "High",
                    "driver": "Mortgage renewals",
                    "sourceLabel": "Canadian bank exposure map",
                    "sourceType": "Sector model placeholder",
                    "sourceQuality": "Medium",
                },
                {
                    "claim": "Provision expense is the swing factor that can turn rate-cut relief into ROE pressure.",
                    "type": "Framework inference",
                    "confidence": "Medium",
                    "importance": "High",
                    "driver": "Provisions",
                    "sourceLabel": "Credit cycle framework",
                    "sourceType": "Internal framework",
                    "sourceQuality": "Medium",
                },
            ],
            "stage": {
                "name": "Framework Agent",
                "role": "Selects the analytical lens for the transmission chain.",
                "status": "complete",
                "duration": "00:07",
                "output": [
                    "Framework: monetary transmission + credit cycle",
                    "Primary tension: NII pressure versus provision relief and valuation support",
                ],
            },
        }
    )
