import type { DemoResearchRun } from "@/lib/types";

export const demoResearchRun: DemoResearchRun = {
  question: "How would rate cuts affect Canadian banks?",
  classification: "macro_to_sector_shock",
  timestamp: "Prototype run | hardcoded frontend data",
  scenario: "Bank of Canada easing cycle",
  headline: "Rate cuts create a mixed bank setup: relief for credit and demand, pressure on margin optics.",
  thesis:
    "Canadian banks benefit if lower rates ease borrower stress and revive loan growth, but the first-order earnings effect is not one-way. Net interest margins, deposit repricing, mortgage renewal timing, and recession-signal risk keep the outcome balanced.",
  keyDrivers: [
    "Net interest margin",
    "Loan growth",
    "Credit losses",
    "Deposit costs",
    "Valuation multiples",
  ],
  metrics: [
    {
      label: "Policy shock",
      value: "-100 bps",
      detail: "Illustrative 12-month easing path",
      tone: "cyan",
    },
    {
      label: "Credit impulse",
      value: "Improving",
      detail: "Borrower stress eases with a lag",
      tone: "emerald",
    },
    {
      label: "NIM pressure",
      value: "Medium",
      detail: "Asset yields reprice faster than some funding costs",
      tone: "amber",
    },
    {
      label: "Skeptic flag",
      value: "Recession signal",
      detail: "Cuts can arrive because growth is deteriorating",
      tone: "rose",
    },
  ],
  agents: [
    {
      name: "Planner Agent",
      role: "Classifies the question and extracts the sector driver map.",
      status: "complete",
      duration: "00:06",
      output: [
        "Research type: macro_to_sector_shock",
        "Shock: rate cuts",
        "Affected sector: Canadian banks",
        "Drivers: NIM, loan growth, credit losses, deposit costs, valuation multiples",
      ],
    },
    {
      name: "Data Agent",
      role: "Stages macro and banking indicators for the demo run.",
      status: "complete",
      duration: "00:09",
      output: [
        "Policy-rate path staged",
        "Yield-curve and credit-stress placeholders attached",
        "No live FRED or market-data calls in Milestone 1",
      ],
    },
    {
      name: "Framework Agent",
      role: "Selects the analytical lens for the transmission chain.",
      status: "complete",
      duration: "00:07",
      output: [
        "Framework: monetary transmission + credit cycle",
        "Primary tension: NIM pressure versus lower losses and stronger volumes",
      ],
    },
    {
      name: "Skeptic Agent",
      role: "Challenges the clean bullish interpretation.",
      status: "complete",
      duration: "00:05",
      output: [
        "Cuts can signal weakening growth",
        "Housing and unemployment data can dominate the rate effect",
        "Deposit beta assumptions are uncertain",
      ],
    },
    {
      name: "Synthesis Agent",
      role: "Produces the map, evidence board, bull/bear view, and memo.",
      status: "complete",
      duration: "00:08",
      output: [
        "Transmission map assembled",
        "Claims labeled by evidence type",
        "Memo avoids recommendations and price targets",
      ],
    },
  ],
  transmissionNodes: [
    {
      id: "rate-cuts",
      label: "Rate cuts",
      subtitle: "BoC policy-rate easing",
      driver: "Policy shock",
      evidenceType: "Framework inference",
      confidence: "High",
      polarity: "neutral",
      x: 0,
      y: 180,
    },
    {
      id: "short-yields",
      label: "Lower short-term yields",
      subtitle: "Assets reprice downward",
      driver: "Net interest margin",
      evidenceType: "Framework inference",
      confidence: "Medium/High",
      polarity: "negative",
      x: 320,
      y: 40,
    },
    {
      id: "nim-pressure",
      label: "Potential NIM pressure",
      subtitle: "Margin optics can soften first",
      driver: "NIM",
      evidenceType: "Framework inference",
      confidence: "Medium",
      polarity: "negative",
      x: 650,
      y: 40,
    },
    {
      id: "borrowing-costs",
      label: "Lower borrowing costs",
      subtitle: "Household and business rates ease",
      driver: "Loan demand",
      evidenceType: "Framework inference",
      confidence: "Medium",
      polarity: "positive",
      x: 320,
      y: 155,
    },
    {
      id: "loan-demand",
      label: "Stronger loan demand",
      subtitle: "Volumes recover with a lag",
      driver: "Loan growth",
      evidenceType: "Framework inference",
      confidence: "Medium",
      polarity: "positive",
      x: 650,
      y: 155,
    },
    {
      id: "financial-conditions",
      label: "Easier financial conditions",
      subtitle: "Debt service burden declines",
      driver: "Credit cycle",
      evidenceType: "Data",
      confidence: "Medium/High",
      polarity: "positive",
      x: 320,
      y: 270,
    },
    {
      id: "credit-stress",
      label: "Lower credit stress",
      subtitle: "Loss pressure may moderate",
      driver: "Credit losses",
      evidenceType: "Data",
      confidence: "Medium",
      polarity: "positive",
      x: 650,
      y: 270,
    },
    {
      id: "discount-rates",
      label: "Lower discount rates",
      subtitle: "Equity duration support",
      driver: "Valuation",
      evidenceType: "Framework inference",
      confidence: "Medium",
      polarity: "positive",
      x: 320,
      y: 385,
    },
    {
      id: "valuation-multiples",
      label: "Higher valuation multiples",
      subtitle: "If earnings risk stays contained",
      driver: "Valuation multiple",
      evidenceType: "Framework inference",
      confidence: "Low/Medium",
      polarity: "mixed",
      x: 650,
      y: 385,
    },
    {
      id: "recession-risk",
      label: "Recession signal risk",
      subtitle: "Cuts may reflect weak growth",
      driver: "Macro regime",
      evidenceType: "Open question",
      confidence: "Medium",
      polarity: "risk",
      x: 320,
      y: 500,
    },
    {
      id: "provisions-growth",
      label: "Higher provisions / weaker growth",
      subtitle: "The key bear-case offset",
      driver: "Provisions",
      evidenceType: "Open question",
      confidence: "Medium",
      polarity: "risk",
      x: 650,
      y: 500,
    },
  ],
  transmissionEdges: [
    {
      id: "e1",
      source: "rate-cuts",
      target: "short-yields",
      label: "reprices",
      polarity: "negative",
    },
    {
      id: "e2",
      source: "short-yields",
      target: "nim-pressure",
      label: "compresses spread",
      polarity: "negative",
    },
    {
      id: "e3",
      source: "rate-cuts",
      target: "borrowing-costs",
      label: "reduces",
      polarity: "positive",
    },
    {
      id: "e4",
      source: "borrowing-costs",
      target: "loan-demand",
      label: "supports",
      polarity: "positive",
    },
    {
      id: "e5",
      source: "rate-cuts",
      target: "financial-conditions",
      label: "eases",
      polarity: "positive",
    },
    {
      id: "e6",
      source: "financial-conditions",
      target: "credit-stress",
      label: "may lower",
      polarity: "positive",
    },
    {
      id: "e7",
      source: "rate-cuts",
      target: "discount-rates",
      label: "lowers",
      polarity: "positive",
    },
    {
      id: "e8",
      source: "discount-rates",
      target: "valuation-multiples",
      label: "can lift",
      polarity: "mixed",
    },
    {
      id: "e9",
      source: "rate-cuts",
      target: "recession-risk",
      label: "may signal",
      polarity: "risk",
    },
    {
      id: "e10",
      source: "recession-risk",
      target: "provisions-growth",
      label: "worsens",
      polarity: "risk",
    },
  ],
  charts: [
    {
      title: "Policy rate path",
      subtitle: "Illustrative easing cycle",
      unit: "%",
      tone: "cyan",
      data: [
        { period: "Q1", value: 5.0 },
        { period: "Q2", value: 4.75 },
        { period: "Q3", value: 4.25 },
        { period: "Q4", value: 4.0 },
        { period: "Q5", value: 3.75 },
      ],
    },
    {
      title: "Bank NIM index",
      subtitle: "Margin pressure first, then stabilization",
      unit: "idx",
      tone: "amber",
      data: [
        { period: "Q1", value: 100, comparison: 100 },
        { period: "Q2", value: 98, comparison: 101 },
        { period: "Q3", value: 96, comparison: 101 },
        { period: "Q4", value: 97, comparison: 100 },
        { period: "Q5", value: 99, comparison: 100 },
      ],
    },
    {
      title: "Loan growth impulse",
      subtitle: "Demand response with a lag",
      unit: "%",
      tone: "emerald",
      data: [
        { period: "Q1", value: 1.2 },
        { period: "Q2", value: 1.4 },
        { period: "Q3", value: 1.8 },
        { period: "Q4", value: 2.4 },
        { period: "Q5", value: 2.9 },
      ],
    },
    {
      title: "Credit stress proxy",
      subtitle: "Watch unemployment and delinquencies",
      unit: "idx",
      tone: "rose",
      data: [
        { period: "Q1", value: 68 },
        { period: "Q2", value: 72 },
        { period: "Q3", value: 70 },
        { period: "Q4", value: 65 },
        { period: "Q5", value: 60 },
      ],
    },
  ],
  evidence: [
    {
      claim: "Rate cuts can pressure bank NIMs when asset yields reprice faster than funding costs.",
      type: "Framework inference",
      confidence: "Medium",
      importance: "High",
      driver: "NIM",
    },
    {
      claim: "Lower borrowing costs may support mortgage and commercial loan demand with a lag.",
      type: "Framework inference",
      confidence: "Medium",
      importance: "Medium",
      driver: "Loan growth",
    },
    {
      claim: "Credit outcomes depend heavily on unemployment, housing, and refinancing stress.",
      type: "Data",
      confidence: "High",
      importance: "High",
      driver: "Credit losses",
    },
    {
      claim: "Investors may reward lower discount rates only if earnings revisions remain contained.",
      type: "Narrative signal",
      confidence: "Low/Medium",
      importance: "Medium",
      driver: "Valuation multiple",
    },
    {
      claim: "The central unresolved issue is whether cuts reflect normalization or recession risk.",
      type: "Open question",
      confidence: "Medium",
      importance: "High",
      driver: "Macro regime",
    },
  ],
  bullCase: {
    title: "Constructive transmission",
    points: [
      "Lower debt-service costs relieve household and small-business stress.",
      "Loan demand can recover after a lag, especially in mortgages and secured credit.",
      "Credit losses may peak earlier if unemployment stays contained.",
      "Lower discount rates can support valuation multiples without implying a recommendation.",
    ],
  },
  bearCase: {
    title: "Adverse transmission",
    points: [
      "Initial rate cuts may be a signal that growth and labor conditions are deteriorating.",
      "Asset-yield repricing can pressure NIM before funding benefits fully appear.",
      "Canadian housing exposure keeps the credit-loss path highly sensitive.",
      "Multiple expansion can be offset by weaker earnings revisions and higher provisions.",
    ],
  },
  memo: [
    {
      title: "Bottom line",
      body: "Rate cuts are not mechanically bullish for Canadian banks. The demo view is balanced: easing can reduce credit stress and revive loan growth, but the first observable earnings pressure may appear in margin and provision assumptions.",
    },
    {
      title: "Most important driver",
      body: "The decisive branch is the recession-signal path. If cuts happen alongside stable employment and controlled delinquencies, the credit and valuation branches improve. If cuts arrive because growth is rolling over, provisions and loan growth can dominate the benefit.",
    },
    {
      title: "Evidence standard",
      body: "This prototype labels claims as data, framework inference, narrative signal, or open question. It does not present price targets, buy/sell calls, or unsupported company-specific conclusions.",
    },
  ],
  openQuestions: [
    {
      question: "Are cuts driven by disinflation normalization or by a deteriorating labor market?",
      whyItMatters: "This determines whether credit relief or provision risk dominates.",
      owner: "Macro data follow-up",
    },
    {
      question: "How quickly do Canadian bank assets and deposits reprice under this scenario?",
      whyItMatters: "Deposit beta and mortgage renewal timing shape the NIM path.",
      owner: "Bank model follow-up",
    },
    {
      question: "Which loan books are most exposed to household refinancing stress?",
      whyItMatters: "Housing and consumer-credit sensitivity can change the bull/bear balance.",
      owner: "Sector diligence",
    },
  ],
};
